// Structural checks for data/boundaries.json (the map's time-driven border layer).
// They only REPORT: nothing here changes, simplifies or invents geometry. The file is
// generated by scripts/ingest-boundaries.js; fixes belong there or in
// scripts/boundary-corrections.js, never in the generated file.
//
// No hard dependency: the overlap check needs @turf/turf (a root devDependency), which the
// caller passes in, so the property/continuity checks and their tests also run where only
// Node is installed (CI's unit-test step and the refresh workflow run before `npm ci`).
import { BOUNDARY_STATUS_LABELS } from "../../app/src/components/mapBorders.js";

// Every feature carries these keys (null allowed for status). name/years/source missing is
// an error; a missing status or note KEY is a warning (the value null is fine).
export const REQUIRED_PROPERTIES = ["name", "start_year", "end_year", "source"];
export const EXPECTED_KEYS = ["status", "note"];
// end_year 9999 = "still current" (scripts/ingest-boundaries.js).
export const OPEN_END_YEAR = 9999;
export const KNOWN_STATUSES = Object.keys(BOUNDARY_STATUS_LABELS);

// Intentional overlays: a shape whose status ends in "-included" CONTAINS a flagged area that
// is drawn on top of it as its own shape (app/src/components/mapBorders.js, isDashedStatus;
// e.g. Israel from 1967 with the West Bank, Gaza Strip and Golan Heights). An overlap is
// expected only between such a shape and a feature that itself carries a status flag.
export const INTENTIONAL_OVERLAY_STATUSES = ["occupied-territory-included", "shared-sovereignty-included"];

// Two separately sourced lines along one border never coincide exactly; on the current data
// the slivers this leaves are at most ~0.13 km2. Overlaps below this size are counted, not listed.
export const OVERLAP_MIN_KM2 = 0.5;

const yearLabel = (y) => (y === OPEN_END_YEAR ? "present" : String(y));
const span = (a, b) => (a === b ? yearLabel(a) : `${yearLabel(a)}-${yearLabel(b)}`);
const label = (p) => `${p?.name ?? "(no name)"} ${span(p?.start_year, p?.end_year)}`;

export function checkProperties(features) {
  const errors = [];
  const warnings = [];
  features.forEach((f, i) => {
    const p = f?.properties;
    const where = `features[${i}] ${label(p)}`;
    if (!p || typeof p !== "object") return errors.push(`${where}: no properties`);
    for (const k of REQUIRED_PROPERTIES) if (!(k in p)) errors.push(`${where}: missing "${k}"`);
    if (typeof p.name !== "string" || !p.name.trim()) errors.push(`${where}: name must be a non-empty string`);
    if (!Number.isInteger(p.start_year) || !Number.isInteger(p.end_year)) errors.push(`${where}: start_year/end_year must be integers`);
    else if (p.start_year > p.end_year) errors.push(`${where}: start_year after end_year`);
    if ("source" in p && (typeof p.source !== "string" || !p.source.trim())) errors.push(`${where}: source must be a non-empty string`);
    for (const k of EXPECTED_KEYS) {
      if (!(k in p)) warnings.push(`${where}: no "${k}" key (other features use ${k}: null when there is none)`);
    }
    if (p.status != null) {
      if (typeof p.status !== "string") errors.push(`${where}: status must be a string or null`);
      else if (!KNOWN_STATUSES.includes(p.status)) warnings.push(`${where}: status "${p.status}" has no label in app/src/components/mapBorders.js`);
    }
    const g = f?.geometry;
    if (!g || !["Polygon", "MultiPolygon"].includes(g.type) || !Array.isArray(g.coordinates) || !g.coordinates.length) {
      errors.push(`${where}: geometry must be a non-empty Polygon or MultiPolygon`);
    }
  });
  return { errors, warnings };
}

// Per name: year ranges must not overlap (one name drawn twice in a year is an error) and
// gaps between them are reported (a warning: e.g. a state renamed or annexed for a while).
export function checkNameContinuity(features) {
  const errors = [];
  const warnings = [];
  const byName = new Map();
  for (const f of features) {
    const p = f?.properties;
    if (typeof p?.name !== "string" || !Number.isInteger(p.start_year) || !Number.isInteger(p.end_year)) continue;
    if (!byName.has(p.name)) byName.set(p.name, []);
    byName.get(p.name).push([p.start_year, p.end_year]);
  }
  for (const [name, ranges] of byName) {
    ranges.sort((a, b) => a[0] - b[0]);
    for (let k = 1; k < ranges.length; k++) {
      const [ps, pe] = ranges[k - 1];
      const [s, e] = ranges[k];
      if (s <= pe) errors.push(`${name}: ${span(ps, pe)} and ${span(s, e)} overlap in years`);
      else if (s > pe + 1) warnings.push(`${name}: no shape for ${span(pe + 1, s - 1)} (between ${span(ps, pe)} and ${span(s, e)})`);
    }
  }
  return { errors, warnings };
}

const bboxesTouch = (a, b) => !(a[0] > b[2] || b[0] > a[2] || a[1] > b[3] || b[1] > a[3]);

// Pairs of features shown in the same year whose areas overlap. Each pair is computed once
// (a feature's geometry is fixed over its year range). Returns all overlaps of at least
// minKm2, each marked `intentional` per INTENTIONAL_OVERLAY_STATUSES, and the number of
// smaller slivers. `turf` is the @turf/turf module.
export function findOverlaps(features, { turf, minKm2 = OVERLAP_MIN_KM2 } = {}) {
  if (!turf) throw new Error("findOverlaps needs the @turf/turf module as opts.turf");
  const overlaps = [];
  let slivers = 0;
  const boxes = features.map((f) => turf.bbox(f));
  for (let i = 0; i < features.length; i++) {
    for (let j = i + 1; j < features.length; j++) {
      const a = features[i].properties;
      const b = features[j].properties;
      const from = Math.max(a.start_year, b.start_year);
      const to = Math.min(a.end_year, b.end_year);
      if (from > to || !bboxesTouch(boxes[i], boxes[j])) continue;
      const x = turf.intersect(turf.featureCollection([features[i], features[j]]));
      if (!x) continue;
      const km2 = turf.area(x) / 1e6;
      if (km2 < minKm2) {
        if (km2 > 0) slivers++;
        continue;
      }
      const intentional =
        (INTENTIONAL_OVERLAY_STATUSES.includes(a.status) && b.status != null) ||
        (INTENTIONAL_OVERLAY_STATUSES.includes(b.status) && a.status != null);
      overlaps.push({ a: label(a), b: label(b), years: span(from, to), km2, intentional });
    }
  }
  return { overlaps, slivers };
}

// ---- self-intersections ----
//
// A PROPER crossing: two segments of one ring whose interiors cross at a single point (each
// segment's endpoints strictly on opposite sides of the other). Rings that only touch at a
// vertex, segments that share an endpoint, and collinear overlaps are not counted. Such a ring
// is invalid GeoJSON (a "bow tie"); renderers and polygon operations may fill or clip it
// unpredictably. Pure arithmetic, no turf: runs in the plain-Node test step too.
const orient = (a, b, c) => (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]);

export function ringCrossings(ring) {
  const n = ring.length - 1; // segments; the ring is closed (last position = first)
  if (n < 4) return [];
  const segs = [];
  for (let i = 0; i < n; i++) {
    const a = ring[i];
    const b = ring[i + 1];
    segs.push({ i, a, b, minX: Math.min(a[0], b[0]), maxX: Math.max(a[0], b[0]), minY: Math.min(a[1], b[1]), maxY: Math.max(a[1], b[1]) });
  }
  // Sweep along x: only segments whose x-ranges overlap are compared.
  const order = [...segs].sort((p, q) => p.minX - q.minX);
  const out = [];
  for (let k = 0; k < order.length; k++) {
    const s = order[k];
    for (let m = k + 1; m < order.length && order[m].minX <= s.maxX; m++) {
      const t = order[m];
      if (t.minY > s.maxY || s.minY > t.maxY) continue;
      const [lo, hi] = s.i < t.i ? [s, t] : [t, s];
      if (hi.i - lo.i === 1 || (lo.i === 0 && hi.i === n - 1)) continue; // neighbours share a vertex
      const d1 = orient(lo.a, lo.b, hi.a);
      const d2 = orient(lo.a, lo.b, hi.b);
      const d3 = orient(hi.a, hi.b, lo.a);
      const d4 = orient(hi.a, hi.b, lo.b);
      if (d1 * d2 < 0 && d3 * d4 < 0) {
        const u = d1 / (d1 - d2); // where hi crosses lo's line, along hi
        const at = [hi.a[0] + u * (hi.b[0] - hi.a[0]), hi.a[1] + u * (hi.b[1] - hi.a[1])];
        out.push({ segments: [lo.i, hi.i], at });
      }
    }
  }
  return out.sort((p, q) => p.segments[0] - q.segments[0] || p.segments[1] - q.segments[1]);
}

// Every proper self-crossing per ring of every feature: [{ feature, crossings: [{ polygon,
// ring, segments, at }] }] (features without any are left out).
export function findSelfIntersections(features) {
  const result = [];
  for (const f of features) {
    const g = f?.geometry;
    if (!g || !["Polygon", "MultiPolygon"].includes(g.type)) continue;
    const polys = g.type === "Polygon" ? [g.coordinates] : g.coordinates;
    const crossings = [];
    polys.forEach((rings, p) => rings.forEach((ring, r) => {
      for (const c of ringCrossings(ring)) crossings.push({ polygon: p, ring: r, ...c });
    }));
    if (crossings.length) result.push({ feature: f, crossings });
  }
  return result;
}

const round6 = (v) => Math.round(v * 1e6) / 1e6;
export function selfIntersectionWarning({ feature, crossings }) {
  const where = crossings
    .map((c) => `polygon ${c.polygon} ring ${c.ring}${c.ring === 0 ? " (outer)" : " (hole)"} segments ${c.segments[0]}/${c.segments[1]} near (${round6(c.at[0])}, ${round6(c.at[1])})`)
    .join("; ");
  return `self-intersection: ${label(feature.properties)}: ${crossings.length} ring crossing(s): ${where}`;
}

// opts.turf: the @turf/turf module; without it the overlap check is skipped (overlaps: null).
export function checkBoundaries(geojson, opts = {}) {
  if (geojson?.type !== "FeatureCollection" || !Array.isArray(geojson.features)) {
    return { errors: ["top level must be a GeoJSON FeatureCollection"], warnings: [], overlaps: null, slivers: 0 };
  }
  const { features } = geojson;
  const props = checkProperties(features);
  const cont = checkNameContinuity(features);
  const errors = [...props.errors, ...cont.errors];
  const warnings = [...props.warnings, ...cont.warnings];
  if (!props.errors.length) for (const s of findSelfIntersections(features)) warnings.push(selfIntersectionWarning(s));
  // Overlap geometry needs valid features; skip it when the structure is already broken.
  if (errors.length || !opts.turf) return { errors, warnings, overlaps: null, slivers: 0 };
  const { overlaps, slivers } = findOverlaps(features, opts);
  for (const o of overlaps.filter((o) => !o.intentional)) {
    warnings.push(`overlap ${o.km2.toFixed(2)} km2 in ${o.years}: ${o.a} x ${o.b}`);
  }
  return { errors, warnings, overlaps, slivers };
}
