// Data access layer. Two very different sources, deliberately:
//
//  - Boundaries, land and the built-in event chunks are
//    static files under public/data/ (generated by scripts/split-data.mjs).
//    They need no query flexibility, so a CDN serves them. Every response is cached in memory for the life of the page
//    and concurrent callers share one in-flight request.
//  - Events: the WHOLE lite set is one static, content-hashed file
//    (events/all.<hash>.json, see loadAllLite). The app loads it once and does
//    range, viewport, category/country, drawn-area and title/snippet matching
//    locally, so a default page load makes ZERO API calls.
//  - Free-text search over full leads uses a static index too (lib/textSearch.js),
//    so the app calls no API at all.

import { eventCoords } from "./geo.js";
import { fullBucket } from "./fullBucket.js";
import { DATA_VERSION } from "./dataVersion.js";

export const DECADE_SIZE = 10;

export function decadeFloor(year) {
  return Math.floor(year / DECADE_SIZE) * DECADE_SIZE;
}

const inFlight = new Map(); // url -> Promise<data>, so concurrent callers share one fetch

// One fetch, optionally cancellable (`signal`) and time-limited (`timeoutMs`).
// A caller-initiated abort rejects with err.aborted === true and NOT as an
// outage; a timeout, network failure or 5xx is err.outage === true; a 4xx is
// a bad request and says nothing about availability.
function fetchJSON(url, { timeoutMs, signal, cache } = {}) {
  const controller = timeoutMs || signal ? new AbortController() : null;
  const timer = timeoutMs ? setTimeout(() => controller.abort(), timeoutMs) : null;
  const onAbort = () => controller.abort();
  if (signal) {
    if (signal.aborted) controller.abort();
    else signal.addEventListener("abort", onAbort, { once: true });
  }
  const init = {};
  if (controller) init.signal = controller.signal;
  if (cache) init.cache = cache;
  return fetch(url, controller || cache ? init : undefined)
    .then((res) => {
      if (!res.ok) {
        const err = new Error(`Failed to load ${url}: ${res.status}`);
        err.outage = res.status >= 500;
        throw err;
      }
      return res.json();
    })
    .catch((err) => {
      if (signal?.aborted) err.aborted = true;
      else if (err.outage === undefined) err.outage = true;
      throw err;
    })
    .finally(() => {
      clearTimeout(timer);
      signal?.removeEventListener("abort", onAbort);
    });
}

function fetchJSONCached(url, { timeoutMs, cache } = {}) {
  if (!inFlight.has(url)) {
    const promise = fetchJSON(url, { timeoutMs, cache });
    // A failed fetch shouldn't be cached forever - let a later retry try again.
    promise.catch(() => inFlight.delete(url));
    inFlight.set(url, promise);
  }
  return inFlight.get(url);
}

const dataUrl = (relPath) => `${import.meta.env.BASE_URL}data/${relPath}`;

// Pure physical geography (land/water silhouette) with no time dimension.
export function loadLand() {
  return fetchJSONCached(dataUrl("land.json"));
}

export function loadBoundaryDecade(decade) {
  return fetchJSONCached(dataUrl(`boundaries/${decade}.json`)); // FeatureCollection
}

function loadEventDecade(decade) {
  return fetchJSONCached(dataUrl(`events/${decade}.json`)); // event[]
}

// Fire-and-forget: warms the cache for a decade without callers waiting on it
// or an error in it propagating anywhere. Used to prefetch neighboring
// boundary decades so crossing a decade boundary while scrubbing the
// timeline rarely has to wait on a fresh request.
export function prefetchBoundaryDecade(decade) {
  loadBoundaryDecade(decade).catch(() => {});
}

export function eventYearRange(e) {
  const start = Number(e.date_start.slice(0, 4));
  const end = e.date_end ? Number(e.date_end.slice(0, 4)) : start;
  return [start, end];
}

export function eventOverlapsRange(e, startYear, endYear) {
  const [s, en] = eventYearRange(e);
  return s <= endYear && en >= startYear;
}

// Canonical event shape for everything downstream. Events without usable
// coordinates are KEPT (location_quality "none", coordinates null): they are
// listed and searchable but never get a map marker. Fields are only ever ADDED
// when missing (location_quality, snippet), never rewritten: titles, dates,
// countries and extracts stay exactly as the source gave them.
function normalizeEvent(e) {
  if (!e || !e.id || !e.date_start) return null;
  const out = e;
  if (!eventCoords(out)) {
    out.coordinates = null;
    out.location_quality = "none";
  } else if (!out.location_quality || out.location_quality === "none") {
    out.location_quality = String(out.coordinate_source ?? "").startsWith("country-fallback")
      ? "approximate"
      : "precise";
  }
  if (out.snippet === undefined && typeof out.extract === "string") {
    out.snippet = out.extract.slice(0, 160);
  }
  return out;
}

export function normalizeEvents(events) {
  const out = [];
  for (const e of events) {
    const n = normalizeEvent(e);
    if (n) out.push(n);
  }
  return out;
}

// Every event in the built-in dataset (lite records), regardless of year, in
// ONE static request: events/all.<DATA_VERSION>.json. The hash in the name makes
// it safe to cache immutably. If that exact file is missing (a stale bundle
// against newer data, or a dev checkout with an old split) the current name is
// read from events/meta.json (fetched no-cache) and, failing that, the decade
// chunks are merged. Concurrent/repeat callers share one load.
let allLitePromise = null;
export function loadAllLite() {
  if (!allLitePromise) {
    const parse = (chunk) => {
      if (!Array.isArray(chunk)) throw new Error("events file is not an array");
      return normalizeEvents(chunk);
    };
    allLitePromise = fetchJSONCached(dataUrl(`events/all.${DATA_VERSION}.json`))
      .then(parse)
      .catch(() =>
        fetchJSON(dataUrl("events/meta.json"), { cache: "no-cache" })
          .then(({ allFile }) => fetchJSONCached(dataUrl(`events/${allFile}`)))
          .then(parse)
      )
      .catch(() =>
        fetchJSON(dataUrl("events/meta.json"), { cache: "no-cache" })
          .then(({ decades }) => Promise.all(decades.map(loadEventDecade)))
          .then((chunks) => {
            const byId = new Map();
            for (const chunk of chunks) for (const e of normalizeEvents(chunk)) byId.set(e.id, e);
            return [...byId.values()];
          })
      );
    allLitePromise.catch(() => {
      allLitePromise = null;
    });
  }
  return allLitePromise;
}

// Resolve one event by id from the static data: events/ids.json maps
// id -> decade chunk. Falls back to scanning every chunk if the map is
// missing (older deployments). Resolves null when unknown.
let idsPromise = null;
export async function loadEventById(id) {
  if (!idsPromise) {
    idsPromise = fetchJSONCached(dataUrl("events/ids.json")).catch(() => null);
  }
  const ids = await idsPromise;
  if (ids && Object.prototype.hasOwnProperty.call(ids, id)) {
    const chunk = await loadEventDecade(ids[id]);
    return normalizeEvents(chunk.filter((e) => e.id === id))[0] ?? null;
  }
  if (ids) return null;
  return (await loadAllLite()).find((e) => e.id === id) ?? null;
}

// data/selection-funnel.json as published by the data pipeline (About page).
export function loadSelectionFunnel() {
  return fetchJSONCached(dataUrl("selection-funnel.json"));
}

// Summary of our framing review (counts by rating and direction), written by split-data.
export function loadFramingReviewSummary() {
  return fetchJSONCached(dataUrl("framing-review.json"));
}

// The full lead of one event: {extract, extract_retrieved_at}. Lives in a small
// static bucket file (events/full/<bucket>.json, see lib/fullBucket.js) that is
// fetched only when an event is opened - lists never download full leads.
// Resolves null if the id is not in its bucket; rejects if the file is unreachable.
export async function loadFullLead(id) {
  const bucket = await fetchJSONCached(dataUrl(`events/full/${fullBucket(id)}.json`));
  return Object.prototype.hasOwnProperty.call(bucket, id) ? bucket[id] : null;
}
