// Data access layer. Two very different sources, deliberately:
//
//  - Boundaries, land, the density index and the built-in event chunks are
//    static files under public/data/ (generated by scripts/split-data.mjs).
//    They need no query flexibility, so a CDN serves them; they never touch
//    the API. Every response is cached in memory for the life of the page
//    and concurrent callers share one in-flight request.
//  - Events are queried from the Redis-backed API (../../../server) with one
//    request per settled year range, plus live full-text search and viewport
//    counts. If VITE_API_URL is unset the app runs in pure static mode, and
//    if the API is down/slow callers fall back to the static event chunks
//    (see loadStaticEvents / searchStaticEvents).

import { eventCoords } from "./geo.js";
import { matchesFilters } from "./ranking.js";
import { fullBucket } from "./fullBucket.js";

export const DECADE_SIZE = 10;

export function decadeFloor(year) {
  return Math.floor(year / DECADE_SIZE) * DECADE_SIZE;
}

// Every decade chunk key a [startYear, endYear] span needs, inclusive.
export function decadesInRange(startYear, endYear) {
  const lo = decadeFloor(Math.min(startYear, endYear));
  const hi = decadeFloor(Math.max(startYear, endYear));
  const decades = [];
  for (let d = lo; d <= hi; d += DECADE_SIZE) decades.push(d);
  return decades;
}

// Deliberately no localhost default: a production build with the variable
// forgotten must not make visitors' browsers call localhost. Dev sets it in
// .env.development.
const API_URL = import.meta.env.VITE_API_URL || "";
export const API_ENABLED = Boolean(API_URL);

const API_TIMEOUT_MS = 8000;

const inFlight = new Map(); // url -> Promise<data>, so concurrent callers share one fetch

// One fetch, optionally cancellable (`signal`) and time-limited (`timeoutMs`).
// A caller-initiated abort rejects with err.aborted === true and NOT as an
// outage; a timeout, network failure or 5xx is err.outage === true; a 4xx is
// a bad request and says nothing about availability.
function fetchJSON(url, { timeoutMs, signal } = {}) {
  const controller = timeoutMs || signal ? new AbortController() : null;
  const timer = timeoutMs ? setTimeout(() => controller.abort(), timeoutMs) : null;
  const onAbort = () => controller.abort();
  if (signal) {
    if (signal.aborted) controller.abort();
    else signal.addEventListener("abort", onAbort, { once: true });
  }
  return fetch(url, controller ? { signal: controller.signal } : undefined)
    .then((res) => {
      if (!res.ok) {
        const err = new Error(`Failed to load ${url}: ${res.status}`);
        err.outage = res.status >= 500;
        throw err;
      }
      return res.json();
    })
    .catch((err) => {
      if (signal?.aborted) err.aborted = true;
      else if (err.outage === undefined) err.outage = true;
      throw err;
    })
    .finally(() => {
      clearTimeout(timer);
      signal?.removeEventListener("abort", onAbort);
    });
}

function fetchJSONCached(url, { timeoutMs } = {}) {
  if (!inFlight.has(url)) {
    const promise = fetchJSON(url, { timeoutMs });
    // A failed fetch shouldn't be cached forever - let a later retry try again.
    promise.catch(() => inFlight.delete(url));
    inFlight.set(url, promise);
  }
  return inFlight.get(url);
}

// Cancellable fetch that de-duplicates identical concurrent requests: callers
// with the same URL share ONE network request, which is only aborted once every
// caller has aborted (on a 0 ms delay, so a synchronous unmount/remount - React
// StrictMode's double effect run, or a re-render that re-issues the same query -
// re-joins the request instead of cancelling and repeating it).
const sharedFetches = new Map(); // url -> {controller, promise, subs, timer}
function fetchJSONShared(url, { timeoutMs, signal }) {
  let s = sharedFetches.get(url);
  if (!s) {
    const controller = new AbortController();
    s = { controller, subs: 0, timer: null };
    const entry = s;
    s.promise = fetchJSON(url, { timeoutMs, signal: controller.signal }).finally(() => {
      if (sharedFetches.get(url) === entry) sharedFetches.delete(url);
    });
    sharedFetches.set(url, s);
  }
  const entry = s;
  clearTimeout(entry.timer);
  entry.subs++;
  return new Promise((resolve, reject) => {
    const onAbort = () => {
      entry.subs--;
      reject(Object.assign(new Error("aborted"), { aborted: true }));
      if (entry.subs === 0) {
        entry.timer = setTimeout(() => {
          if (entry.subs !== 0) return;
          if (sharedFetches.get(url) === entry) sharedFetches.delete(url);
          entry.controller.abort();
        }, 0);
      }
    };
    if (signal.aborted) return onAbort();
    signal.addEventListener("abort", onAbort, { once: true });
    entry.promise.then(resolve, reject).finally(() => signal.removeEventListener("abort", onAbort));
  });
}

function apiUrl(path, params = {}) {
  const url = new URL(path, API_URL);
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null && value !== "") {
      url.searchParams.set(key, value);
    }
  }
  return url.toString();
}

const dataUrl = (relPath) => `${import.meta.env.BASE_URL}data/${relPath}`;

// Pure physical geography (land/water silhouette) with no time dimension.
export function loadLand() {
  return fetchJSONCached(dataUrl("land.json"));
}

// Per-start-year event counts for the timeline density chart, precomputed by
// split-data.mjs so it costs no API request.
export function loadEventsIndex() {
  return fetchJSONCached(dataUrl("events/index.json"));
}

export function loadBoundaryDecade(decade) {
  return fetchJSONCached(dataUrl(`boundaries/${decade}.json`)); // FeatureCollection
}

export function loadEventDecade(decade) {
  return fetchJSONCached(dataUrl(`events/${decade}.json`)); // event[]
}

// Fire-and-forget: warms the cache for a decade without callers waiting on it
// or an error in it propagating anywhere. Used to prefetch neighboring
// boundary decades so crossing a decade boundary while scrubbing the
// timeline rarely has to wait on a fresh request.
export function prefetchBoundaryDecade(decade) {
  loadBoundaryDecade(decade).catch(() => {});
}


export function eventYearRange(e) {
  const start = Number(e.date_start.slice(0, 4));
  const end = e.date_end ? Number(e.date_end.slice(0, 4)) : start;
  return [start, end];
}

export function eventOverlapsRange(e, startYear, endYear) {
  const [s, en] = eventYearRange(e);
  return s <= endYear && en >= startYear;
}

// Canonical event shape for everything downstream. Events without usable
// coordinates are KEPT (location_quality "none", coordinates null): they are
// listed and searchable but never get a map marker. Fields are only ever ADDED
// when missing (location_quality, snippet), never rewritten: titles, dates,
// countries and extracts stay exactly as the source gave them.
export function normalizeEvent(e) {
  if (!e || !e.id || !e.date_start) return null;
  const out = e;
  if (!eventCoords(out)) {
    out.coordinates = null;
    out.location_quality = "none";
  } else if (!out.location_quality || out.location_quality === "none") {
    out.location_quality = String(out.coordinate_source ?? "").startsWith("country-fallback")
      ? "approximate"
      : "precise";
  }
  if (out.snippet === undefined && typeof out.extract === "string") {
    out.snippet = out.extract.slice(0, 160);
  }
  return out;
}

export function normalizeEvents(events) {
  const out = [];
  for (const e of events) {
    const n = normalizeEvent(e);
    if (n) out.push(n);
  }
  return out;
}

// Built-in dataset, filtered client-side to a year range. Chunks overlap
// (an event spanning decades is in each), so dedupe by id.
export async function loadStaticEvents(startYear, endYear) {
  const chunks = await Promise.all(decadesInRange(startYear, endYear).map(loadEventDecade));
  const byId = new Map();
  for (const chunk of chunks) {
    for (const e of normalizeEvents(chunk)) {
      if (eventOverlapsRange(e, startYear, endYear)) byId.set(e.id, e);
    }
  }
  return [...byId.values()];
}

// Every event in the built-in dataset, regardless of year (events outside the
// timeline window live in the edge chunks and are included).
let allStaticPromise = null;
export function loadAllStaticEvents() {
  if (!allStaticPromise) {
    allStaticPromise = fetchJSONCached(dataUrl("events/meta.json"))
      .then(({ decades }) => Promise.all(decades.map(loadEventDecade)))
      .then((chunks) => {
        const byId = new Map();
        for (const chunk of chunks) for (const e of normalizeEvents(chunk)) byId.set(e.id, e);
        return [...byId.values()];
      });
    allStaticPromise.catch(() => {
      allStaticPromise = null;
    });
  }
  return allStaticPromise;
}

// Offline stand-in for the API: same tokenised, diacritic-insensitive
// matching (see lib/ranking.js) plus the area/category/country filters,
// across the whole built-in dataset. Unranked - callers rank with rankEvents.
export async function searchStaticEvents({ q = "", area = null, categories = [], countries = [] } = {}) {
  const all = await loadAllStaticEvents();
  return all.filter((e) => matchesFilters(e, { q, area, categories, countries }));
}

// Resolve one event by id from the static data: events/ids.json maps
// id -> decade chunk. Falls back to scanning every chunk if the map is
// missing (older deployments). Resolves null when unknown.
let idsPromise = null;
export async function loadEventById(id) {
  if (!idsPromise) {
    idsPromise = fetchJSONCached(dataUrl("events/ids.json")).catch(() => null);
  }
  const ids = await idsPromise;
  if (ids && Object.prototype.hasOwnProperty.call(ids, id)) {
    const chunk = await loadEventDecade(ids[id]);
    return normalizeEvents(chunk.filter((e) => e.id === id))[0] ?? null;
  }
  if (ids) return null;
  return (await loadAllStaticEvents()).find((e) => e.id === id) ?? null;
}

// data/selection-funnel.json as published by the data pipeline (About page).
export function loadSelectionFunnel() {
  return fetchJSONCached(dataUrl("selection-funnel.json"));
}

// The full lead of one event: {extract, extract_retrieved_at}. Lives in a small
// static bucket file (events/full/<bucket>.json, see lib/fullBucket.js) that is
// fetched only when an event is opened - lists never download full leads.
// Resolves null if the id is not in its bucket; rejects if the file is unreachable.
export async function loadFullLead(id) {
  const bucket = await fetchJSONCached(dataUrl(`events/full/${fullBucket(id)}.json`));
  return Object.prototype.hasOwnProperty.call(bucket, id) ? bucket[id] : null;
}

// One page of /api/events. Rejects with err.outage === true when the API is
// unreachable, 5xx, or slower than API_TIMEOUT_MS; err.aborted when `signal`
// was aborted. Without `signal` identical requests share one cached fetch.
// Response: { total, truncated, events }.
export function fetchEvents({
  start,
  end,
  bbox,
  q,
  category,
  country,
  precise,
  sort,
  limit,
  offset,
  fields,
  signal,
} = {}) {
  const url = apiUrl("/api/events", {
    start,
    end,
    bbox: bbox ? bbox.join(",") : undefined,
    q,
    category: category?.length ? [].concat(category).join(",") : undefined,
    country: country?.length ? [].concat(country).join(",") : undefined,
    precise: precise ? 1 : undefined,
    sort,
    limit,
    offset: offset || undefined,
    fields,
  });
  const request = signal
    ? fetchJSONShared(url, { timeoutMs: API_TIMEOUT_MS, signal })
    : fetchJSONCached(url, { timeoutMs: API_TIMEOUT_MS });
  return request.then((data) => {
    const events = normalizeEvents(data.events ?? []);
    const received = (data.events ?? []).length;
    const truncated =
      typeof data.truncated === "boolean" ? data.truncated : data.total > (offset || 0) + received;
    return { total: data.total ?? events.length, truncated, events, received };
  });
}

// Pages through a query with offset until the server says it is complete,
// deduplicating by id. If a page adds nothing new (a server that ignores
// `offset`) or maxPages is reached, stops with truncated = true so callers can
// say so instead of silently presenting a partial list.
export async function fetchAllPages(params, { signal, maxPages = 5, pageSize = 1000 } = {}) {
  const byId = new Map();
  let total = 0;
  let truncated = false;
  let offset = 0;
  for (let page = 0; page < maxPages; page++) {
    const res = await fetchEvents({ ...params, limit: pageSize, offset, signal });
    total = res.total;
    const before = byId.size;
    for (const e of res.events) if (!byId.has(e.id)) byId.set(e.id, e);
    truncated = res.truncated;
    if (!truncated) break;
    if (res.received === 0 || (byId.size === before && res.events.length > 0)) break;
    offset += res.received;
  }
  return { total, truncated, events: [...byId.values()] };
}
