// GENERATED by scripts/split-data.mjs - do not edit. Names the content-hashed
// events/all.<hash>.json the app loads on start (see lib/dataClient.js loadAllLite).
export const DATA_VERSION = "c7900c26cd5d";
