// Data access layer. Two very different sources, deliberately:
//
//  - Boundaries, land, the density index and the built-in event chunks are
//    static files under public/data/ (generated by scripts/split-data.mjs).
//    They need no query flexibility, so a CDN serves them; they never touch
//    the API. Every response is cached in memory for the life of the page
//    and concurrent callers share one in-flight request.
//  - Events are queried from the Redis-backed API (../../../server) with one
//    request per settled year range, plus live full-text search and viewport
//    counts. If VITE_API_URL is unset the app runs in pure static mode, and
//    if the API is down/slow callers fall back to the static event chunks
//    (see loadStaticEvents / searchStaticEvents).

export const DECADE_SIZE = 10;

export function decadeFloor(year) {
  return Math.floor(year / DECADE_SIZE) * DECADE_SIZE;
}

// Every decade chunk key a [startYear, endYear] span needs, inclusive.
export function decadesInRange(startYear, endYear) {
  const lo = decadeFloor(Math.min(startYear, endYear));
  const hi = decadeFloor(Math.max(startYear, endYear));
  const decades = [];
  for (let d = lo; d <= hi; d += DECADE_SIZE) decades.push(d);
  return decades;
}

// Deliberately no localhost default: a production build with the variable
// forgotten must not make visitors' browsers call localhost. Dev sets it in
// .env.development.
const API_URL = import.meta.env.VITE_API_URL || "";
export const API_ENABLED = Boolean(API_URL);

const API_TIMEOUT_MS = 8000;

const inFlight = new Map(); // url -> Promise<data>, so concurrent callers share one fetch

function fetchJSONCached(url, { timeoutMs } = {}) {
  if (!inFlight.has(url)) {
    const controller = timeoutMs ? new AbortController() : null;
    const timer = timeoutMs ? setTimeout(() => controller.abort(), timeoutMs) : null;
    const promise = fetch(url, controller ? { signal: controller.signal } : undefined)
      .then((res) => {
        if (!res.ok) {
          const err = new Error(`Failed to load ${url}: ${res.status}`);
          err.outage = res.status >= 500;
          throw err;
        }
        return res.json();
      })
      .catch((err) => {
        // Network failure, timeout/abort or a 5xx all mean "API unavailable";
        // a 4xx is a bad request and says nothing about availability.
        if (err.outage === undefined) err.outage = true;
        throw err;
      })
      .finally(() => clearTimeout(timer));
    // A failed fetch shouldn't be cached forever - let a later retry try again.
    promise.catch(() => inFlight.delete(url));
    inFlight.set(url, promise);
  }
  return inFlight.get(url);
}

function apiUrl(path, params = {}) {
  const url = new URL(path, API_URL);
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== null && value !== "") {
      url.searchParams.set(key, value);
    }
  }
  return url.toString();
}

const dataUrl = (relPath) => `${import.meta.env.BASE_URL}data/${relPath}`;

// Pure physical geography (land/water silhouette) with no time dimension.
export function loadLand() {
  return fetchJSONCached(dataUrl("land.json"));
}

// Per-start-year event counts for the timeline density chart, precomputed by
// split-data.mjs so it costs no API request.
export function loadEventsIndex() {
  return fetchJSONCached(dataUrl("events/index.json"));
}

export function loadBoundaryDecade(decade) {
  return fetchJSONCached(dataUrl(`boundaries/${decade}.json`)); // FeatureCollection
}

export function loadEventDecade(decade) {
  return fetchJSONCached(dataUrl(`events/${decade}.json`)); // event[]
}

// Fire-and-forget: warms the cache for a decade without callers waiting on it
// or an error in it propagating anywhere. Used to prefetch neighboring
// boundary decades so crossing a decade boundary while scrubbing the
// timeline rarely has to wait on a fresh request.
export function prefetchBoundaryDecade(decade) {
  loadBoundaryDecade(decade).catch(() => {});
}

function eventYearRange(e) {
  const start = Number(e.date_start.slice(0, 4));
  const end = e.date_end ? Number(e.date_end.slice(0, 4)) : start;
  return [start, end];
}

export function eventOverlapsRange(e, startYear, endYear) {
  const [s, en] = eventYearRange(e);
  return s <= endYear && en >= startYear;
}

// Built-in dataset, filtered client-side to a year range. Chunks overlap
// (an event spanning decades is in each), so dedupe by id.
export async function loadStaticEvents(startYear, endYear) {
  const chunks = await Promise.all(decadesInRange(startYear, endYear).map(loadEventDecade));
  const byId = new Map();
  for (const chunk of chunks) {
    for (const e of chunk) {
      if (eventOverlapsRange(e, startYear, endYear)) byId.set(e.id, e);
    }
  }
  return [...byId.values()];
}

// Client-side stand-in for full-text search: case-insensitive substring over
// title + extract, across the whole built-in dataset.
export async function searchStaticEvents(query) {
  const needle = query.toLowerCase();
  const { minYear, maxYear } = await fetchJSONCached(dataUrl("events/meta.json"));
  const all = await loadStaticEvents(minYear, maxYear);
  return all.filter((e) => `${e.title} ${e.extract ?? ""}`.toLowerCase().includes(needle));
}

// Arbitrary [start,end] x bbox x full-text query against the API. Rejects
// with err.outage === true when the API is unreachable, 5xx, or slower than
// API_TIMEOUT_MS. `start`/`end` are optional - omit both to search the whole
// timeline.
export function fetchEvents({ start, end, bbox, q } = {}) {
  const url = apiUrl("/api/events", {
    start,
    end,
    bbox: bbox ? bbox.join(",") : undefined,
    q,
  });
  return fetchJSONCached(url, { timeoutMs: API_TIMEOUT_MS }); // { total, events }
}
